apiVersion: v1
kind:  Service
metadata:
  name: laravel
  namespace: production
spec:
  type: ClusterIP
  selector: 
    app: laravel
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80