apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  namespace: staging
spec:
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel
        image: hiro99/laravel:0.0.1-stg
        ports:
        - containerPort: 80
          name: laravel