apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-lara
  namespace: staging
spec:
  selector:
    matchLabels:
      app: mysql-lara
  template:
    metadata:
      labels:
        app: mysql-lara
    spec:
      containers:
      - name: mysql-lara
        image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
        envFrom:
          - secretRef:
              name: lara-mysql-secret
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-lara-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-lara-data
        persistentVolumeClaim:
          claimName: lara-mysql-pvc