apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
  namespace: staging
  labels:
    app: landing-page
    name: landing-page
    keel.sh/policy: major
    keel.sh/trigger: poll
    keel.sh/approvals: "1"
spec:	
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      name: landing-page
      labels:
        app: landing-page
    spec:
#      imagePullSecrets:
#      - name: dockerhub-private
      containers:
      - name: landing-page
        image: 637631085186.dkr.ecr.ap-southeast-1.amazonaws.com/landing:0.0.16-stg
        ports:
        - containerPort: 80