apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-pesbuk
  namespace: staging
  labels:
    app: pesbuk
    name: pesbuk
    keel.sh/policy: major
    keel.sh/trigger: poll
    keel.sh/approvals: "1"
spec:
  selector:
    matchLabels:
      app: pesbuk
  template:
    metadata:
      labels:
        app: pesbuk
    spec:
      containers:
      - name: pesbuk
        image: 637631085186.dkr.ecr.ap-southeast-1.amazonaws.com/pesbuk:0.0.3-stg
        ports:
        - containerPort: 80
        env:
          - name: HOST
            value: service-mysql-pes.staging.svc.cluster.local
          - name: USER
            value: root
          - name: PASS
            value: pesbuk
          - name: DBNAME
            value: dbsosmed