apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-fesbuk
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: pesbuk-stg.pastikerja.xyz
    http: 
      paths:
      - backend:
          serviceName: svc-pesbuk
          servicePort: 80
